name: Prettier Linter check

on:
  push:
  pull_request:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v22.7.0

      - name: Install dependencies
        run: yarn install

      - name: Run Prettier
        run: yarn tsc --noEmit .
