name: TypeScript Syntax Error Check

on:
  push:
  pull_request:
    branches: [master]

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Run TypeScript Check
        run: yarn tsc --noEmit
